const ZH_TIPS = {
  "about-you": [
    "我先看看这些材料里，哪些判断反复出现。",
    "有些方法不会直接写出来，它们藏在你的取舍里。",
    "案例里的转折，往往比结论更有线索。",
    "同一类问题，你每次都怎么处理？这里可能有答案。",
    "我在找你的重点，不急着把所有东西都塞进来。",
    "有时候，一句“这里不能这么做”很关键。",
    "两个答案都能成立时，你为什么选其中一个？",
    "我会把不确定的地方整理成问题，留给你判断。",
    "经验最有价值的部分，常常是当时的现场感。",
    "我在分辨哪些是通用知识，哪些是你的方法。",
    "重复出现的例子，可能指向一条稳定的路径。",
    "你的语气里，也藏着你希望别人怎么做。",
    "不是所有细节都要留下，重要的是判断的骨架。",
    "我在关注你什么时候会改变做法。",
    "例外情况往往能说明方法的边界。",
    "有些线索暂时不确定，没关系，先标记起来。",
    "我会把材料里的不同声音放在一起对照。",
    "你真正坚持的地方，通常比标准答案更重要。",
    "一个小小的取舍，可能比一整段说明更有分量。",
    "我在找“为什么这样做”，不只找“做了什么”。",
    "创作者的判断，常常藏在修改和批注里。",
    "我会把明显的线索和需要确认的线索分开。",
    "当你说“通常”或“除非”时，边界就出现了。",
    "这一步是在认识你的方法，不是在给你打分。",
    "你不需要把自己解释得很完整，真实就够了。",
    "我在整理一张属于这个 Product 的线索图。",
    "有些答案会改变后面的路，我们先把它们找出来。",
    "我会先保留你的差异，再处理表达上的重复。",
    "一个方法之所以有用，通常是因为它有明确取舍。",
    "线索已经开始聚拢，接下来交给你确认关键处。"
  ],
  corpus: [
    "线索开始连成一条可以走的路径。",
    "我正在把你的判断拆成原则、步骤和边界。",
    "原则回答为什么，步骤回答接下来怎么做。",
    "有些知识适合查找，有些判断需要在现场发生。",
    "我在看哪些内容应该成为长期方法。",
    "好的方法不只告诉人做什么，也说明什么时候不要做。",
    "我会把相似的经验合并，把重要的差异留下。",
    "这不是把材料压缩得更短，而是让它更容易被使用。",
    "一条清晰的路径，通常从一个具体结果开始。",
    "我在区分你的观点、例子和真正可复用的动作。",
    "有些内容适合放进知识，有些内容更像操作技巧。",
    "你的标准会决定这套方法最后的形状。",
    "如果一条规则没有例外，它可能还不够接近现场。",
    "我会为方法保留必要的语气和分寸。",
    "边界不是限制 Product，而是让它更可信。",
    "我在检查每条线索能不能支持一个明确动作。",
    "复杂经验可以有很多层，但使用时要能找到入口。",
    "方法不是资料的终点，是别人可以拿来工作的起点。",
    "我会把重复出现的判断编成更稳定的结构。",
    "一套方法既要像你，也要能被别人走通。",
    "我在把隐性的经验，变成可以被调用的部分。",
    "有些答案会成为规则，有些答案只适合保留为例子。",
    "我会先照顾方法的骨架，再处理表达的漂亮。",
    "能说清楚不做什么，往往能让做什么更清楚。",
    "这一步不是替你发明方法，是帮你把已有方法显出来。",
    "不同材料之间的呼应，正在变成 Product 里的结构。",
    "我在留意那些“看情况”背后的判断条件。",
    "一个可用的 Product，需要知道什么时候该停下来。",
    "方法成形以后，还要经过实际情境的检验。",
    "结构已经有了，下一步看看它能不能真正工作。"
  ],
  review: [
    "现在轮到真实情境来问问题了。",
    "我会从不同角度看看这套方法是否仍然像你。",
    "这里不用追求每个答案都漂亮，先看判断对不对。",
    "有些偏差只有换个场景才会露出来。",
    "我在把结果和你的标准放在一起对照。",
    "通过一个案例，说明方向对了，不代表所有路都一样。",
    "如果哪里不对，我们就把那一处标出来。",
    "一次具体的修正，往往比一大段泛泛说明更有帮助。",
    "这里看的是方法能不能稳定工作，不是你能不能答满分。",
    "我会把已经验证的案例留下，给下一版做参照。",
    "好的反馈不一定长，关键是指出偏差在哪里。",
    "有些问题本身不适合拿来判断 Product，这也值得标记。",
    "你可以接受一个结果，也可以告诉我它该怎么改。",
    "我在寻找“哪里不像你”，而不只是“哪里错了”。",
    "回到具体场景，通常比重新解释一遍原则更快。",
    "有些答案看起来合理，但没有真正解决用户的问题。",
    "这里的每个判断，都会影响下一版方法。",
    "我会把通过的部分和需要调整的部分分开。",
    "如果一个结果只在熟悉情境里成立，我们继续换个角度看。",
    "你的不同意见，是这套方法变准的线索。",
    "不用一次把所有问题解决，先处理最影响结果的地方。",
    "我在检查方法有没有保留原来的重点和边界。",
    "一个好的修正，会让下一次遇到类似情境时更稳。",
    "有些失败不是坏消息，它告诉我们规则还缺哪一块。",
    "这里不是考试现场，更像一起看一份工作样本。",
    "你可以保留自己的判断，不必迁就一个看起来标准的答案。",
    "我会把你的反馈带回方法，而不是只改这一道题。",
    "结果变好以后，我们也要确认没有破坏原来已经通过的部分。",
    "这一轮看完，方法会更接近真实交付。",
    "线索已经经过几轮对照，接下来决定它是否可以交付。"
  ],
  brief: [
    "现在要为用户找一个合适的入口。",
    "开始问题不是问得越多越好，而是让工作更快进入状态。",
    "我在看哪些背景会真正改变后面的回答。",
    "一个好问题，常常能替用户省掉很多解释。",
    "这里留下的是必要线索，不是完整的个人档案。",
    "用户带着自己的情境来，我们只需要先知道关键部分。",
    "问题越接近真实工作，后面的交付越容易对上。",
    "我在帮这个 Product 找到第一次对话的节奏。",
    "有些问题适合所有人，有些只在特定情境下出现。",
    "只要能帮助方法开始工作，问题就已经有价值。",
    "这里可以保持简单，复杂度留给 Product 自己处理。",
    "一个清楚的入口，会让用户更快看到结果。",
    "我在区分“必须知道”和“知道了也不改变什么”。",
    "开始问题应该让用户感觉：这正是我现在要解决的事。",
    "问得准确，比问得全面更重要。",
    "有些上下文可以留到对话里，不必一开始全部收齐。",
    "我会把问题放到用户真正需要回答的位置。",
    "好的入口不会抢走用户的注意力。",
    "这里不是设置表单，是为一次具体工作做准备。",
    "一个问题如果不会改变结果，也许可以先放下。",
    "我在让 Product 更快遇到它真正擅长的工作。",
    "用户给出关键背景，方法就有了落脚点。",
    "开始问题可以有创作者的语气，不必像系统提示。",
    "少一点说明，多一点直接进入工作的感觉。",
    "我会保留能帮助你判断的线索，删掉只是增加负担的部分。",
    "一个好的问题，会让用户知道为什么要回答它。",
    "入口清楚以后，后面的体验会自然很多。",
    "这里的每个问题，都在替未来的用户争取一点时间。",
    "问题已经接近它该在的位置了。",
    "入口准备好了，接下来让 Product 开始工作。"
  ],
  complete: [
    "这套方法已经走完了从线索到交付的路。",
    "现在看到的是一个可以被别人使用的 Product。",
    "发布前，我们再一起看一眼它的承诺和边界。",
    "一个清楚的 Product，不需要承诺它做不到的事。",
    "用户买的是一次具体的帮助，不是一个模糊的万能答案。",
    "方法、开始问题和交付结果，现在已经放在一起了。",
    "这一版会成为一个明确的 release，方便之后继续改进。",
    "如果以后要更新，我们可以从新的反馈开始下一版。",
    "现在的重点不是做得更大，而是交付得更清楚。",
    "一个 Product 的价值，最后会落在用户拿走的结果上。",
    "我在确认这套方法是否仍然保留你的差异。",
    "边界写得越清楚，用户越容易知道它适不适合自己。",
    "发布不是结束，是这套方法开始被使用的时刻。",
    "真正的验证，会发生在别人带着自己的问题来使用时。",
    "你不需要把所有能力都放进一个 Product。",
    "先交付一个边界清楚、确实有用的工作。",
    "现在可以把它交给你的受众，看看他们会怎么使用。",
    "用户的真实反馈，会成为下一轮线索。",
    "这套方法已经不只是材料，它现在有了自己的入口和结果。",
    "我会把这次确认保留下来，作为这个版本的一部分。",
    "发布前最后看一眼：用户拿到的结果是否足够具体。",
    "如果一个承诺无法被验证，它可能还需要再收窄一点。",
    "Product 越清楚，用户越容易在正确的时刻找到它。",
    "不用把 Product 说得很大，让它把一件事做好就够了。",
    "这不是把你的全部经验交出去，而是交付一项明确的工作。",
    "方法的价值，现在要从你的判断走向别人的行动。",
    "发布的是已经看过、改过、确认过的一版。",
    "以后每一次真实使用，都会让这套方法更有依据。",
    "线索已经整理完毕，接下来轮到真实世界提供反馈。",
    "准备好了，把这套方法交给真正需要它的人。"
  ]
};

const EN_TIPS = {
  "about-you": [
    "I’m looking for the judgments that keep showing up in your material.",
    "Some methods are not written down; they hide in your choices.",
    "The turn in a case often tells us more than its conclusion.",
    "How do you handle the same kind of problem each time? There may be a clue here.",
    "I’m finding your focus first. We do not need to keep everything.",
    "Sometimes a simple “not this way” is the important clue.",
    "When two answers work, what makes you choose one?",
    "I’ll turn uncertain parts into questions for you to judge.",
    "The most useful part of experience is often what the moment felt like.",
    "I’m separating general knowledge from your way of working.",
    "Repeated examples may point to a dependable path.",
    "Your tone also tells us how you want people to act.",
    "We do not need every detail; we need the shape of the judgment.",
    "I’m watching for the moments when you change your approach.",
    "Exceptions often show where a method stops applying.",
    "Some clues are still uncertain. Marking them is enough for now.",
    "I’m putting the different voices in your material side by side.",
    "What you insist on usually matters more than a standard answer.",
    "A small trade-off can carry more weight than a full explanation.",
    "I’m looking for why you did it, not only what you did.",
    "A creator’s judgment often lives in edits and notes.",
    "I’ll separate clear clues from clues that need your confirmation.",
    "Words like “usually” and “unless” reveal the boundary.",
    "This step is about understanding your method, not grading you.",
    "You do not need to explain yourself perfectly. Real is enough.",
    "I’m mapping the clues that belong to this Product.",
    "Some answers will change the path ahead. Let’s find those first.",
    "I’ll keep your differences before I clean up repetition.",
    "A method is useful because it makes a clear trade-off.",
    "The clues are gathering. Next, you can confirm the important ones."
  ],
  corpus: [
    "The clues are starting to form a path we can follow.",
    "I’m separating your judgments into principles, steps, and boundaries.",
    "Principles explain why; steps explain what to do next.",
    "Some knowledge is for lookup. Some judgment has to happen in the moment.",
    "I’m looking for what should become a lasting method.",
    "A good method says what to do and when not to do it.",
    "I’ll combine similar experiences and keep the meaningful differences.",
    "This is not about making the material shorter; it is about making it usable.",
    "A clear path usually starts with a concrete result.",
    "I’m separating opinions, examples, and reusable actions.",
    "Some content belongs in knowledge; some is closer to a practical move.",
    "Your standards will shape the method.",
    "A rule with no exceptions may still be too far from the real world.",
    "I’ll keep the right tone and restraint in the method.",
    "A boundary does not limit the Product; it makes it more credible.",
    "I’m checking whether each clue can support a clear action.",
    "Complex experience can have layers, but users still need an entry point.",
    "A method is not the end of the material. It is where work can begin.",
    "I’m turning repeated judgments into a steadier structure.",
    "A method should sound like you and still be possible to follow.",
    "I’m making the implicit parts of your experience callable.",
    "Some answers become rules; others are better kept as examples.",
    "I’ll take care of the method’s spine before polishing the language.",
    "Knowing what not to do often makes the next action clearer.",
    "I’m not inventing a method for you; I’m making yours visible.",
    "Echoes across the material are becoming Product structure.",
    "I’m watching the conditions behind “it depends.”",
    "A usable Product needs to know when to stop.",
    "Once the method takes shape, real situations still have to test it.",
    "The structure is here. Next, we see whether it actually works."
  ],
  review: [
    "Now real situations get to ask the questions.",
    "I’m checking whether the method still sounds like you from different angles.",
    "The goal is not a pretty answer; it is the right judgment.",
    "Some gaps only appear when the situation changes.",
    "I’m comparing the result with your standard.",
    "One good case shows direction, not that every path is identical.",
    "If something is off, we’ll mark that exact place.",
    "A concrete correction usually helps more than a broad explanation.",
    "We’re checking whether the method works steadily, not whether it gets a perfect score.",
    "I’ll keep the cases that have been checked as references for the next version.",
    "Useful feedback does not need to be long. It needs to locate the gap.",
    "Some questions are not good tests for this Product. That is useful to mark too.",
    "You can accept a result or tell me how it should change.",
    "I’m looking for what does not sound like you, not only what is wrong.",
    "Returning to the situation is often faster than restating the principle.",
    "An answer can sound reasonable and still miss the user’s problem.",
    "Every judgment here will shape the next version.",
    "I’ll separate what passed from what needs adjustment.",
    "If a result only works in familiar situations, we’ll change the angle.",
    "Your disagreement is a clue that makes the method sharper.",
    "We do not need to solve everything at once. Start with the biggest effect.",
    "I’m checking that the original focus and boundaries survived.",
    "A good correction makes the next similar situation steadier.",
    "A failure is not always bad news; it shows which rule is missing.",
    "This is not an exam. It is a work sample we are looking at together.",
    "You can keep your judgment instead of fitting a standard answer.",
    "I’ll carry your feedback back into the method, not just this question.",
    "When a result improves, we still check that earlier passes stayed intact.",
    "After this round, the method will be closer to real delivery.",
    "The clues have been compared. Next, we decide whether they are ready to ship."
  ],
  brief: [
    "Now we’re finding the right entry point for the user.",
    "Starting questions should get work moving, not collect everything.",
    "I’m looking for the context that will actually change the answer.",
    "A good question can save the user a lot of explanation.",
    "Keep the useful clues, not a complete personal file.",
    "The user brings a situation; we only need the important part first.",
    "The closer a question is to real work, the easier the delivery can land.",
    "I’m finding the rhythm for the Product’s first conversation.",
    "Some questions fit everyone; others belong to a specific situation.",
    "If a question helps the method start, it already has value.",
    "Keep this simple. Let the Product hold the complexity.",
    "A clear entry helps the user reach a result sooner.",
    "I’m separating must-know context from context that changes nothing.",
    "A starting question should feel like the user’s actual problem.",
    "Precise is more useful than comprehensive.",
    "Some context can wait for the conversation.",
    "I’m placing each question where the user needs it.",
    "A good entry does not steal the user’s attention.",
    "This is preparation for a real piece of work, not a settings form.",
    "If a question will not change the result, it can wait.",
    "I’m helping the Product reach the work it is good at sooner.",
    "The user’s key context gives the method somewhere to land.",
    "Starting questions can sound like a creator, not a system prompt.",
    "Less explanation, more feeling of getting to work.",
    "I’ll keep clues that help judgment and remove extra burden.",
    "A good question makes its reason clear.",
    "Once the entry is clear, the rest feels more natural.",
    "Each question saves a little time for a future user.",
    "The questions are close to where they belong.",
    "The entry is ready. Next, let the Product do its work."
  ],
  complete: [
    "This method has travelled from clues to delivery.",
    "What you see now is a Product someone else can use.",
    "Before publishing, let’s look once more at its promise and boundaries.",
    "A clear Product does not promise what it cannot do.",
    "Users buy a specific kind of help, not a vague universal answer.",
    "The method, starting questions, and result are now together.",
    "This version becomes a clear release we can improve later.",
    "When it is time to update, we can start from new feedback.",
    "The priority is not to make it bigger, but clearer to deliver.",
    "A Product’s value lands in the result a user takes away.",
    "I’m checking that the method still keeps your difference.",
    "Clear boundaries help users know whether it fits them.",
    "Publishing is when the method starts being used.",
    "Real validation happens when someone brings their own problem.",
    "You do not need to put every capability into one Product.",
    "Deliver one clear piece of work that is genuinely useful.",
    "Now you can hand it to your audience and see how they use it.",
    "Real user feedback becomes the next round of clues.",
    "This is no longer just material; it has an entry and an outcome.",
    "I’ll keep this confirmation as part of the version.",
    "One last check: is the result specific enough for the user?",
    "If a promise cannot be tested, it may need to get narrower.",
    "The clearer the Product, the easier it is to find at the right moment.",
    "You do not need to make it sound huge. Let it do one thing well.",
    "This is not handing over all your experience; it is delivering one clear job.",
    "The value of the method is moving from your judgment to someone else’s action.",
    "This release has been seen, changed, and confirmed.",
    "Every real use will give the method more evidence.",
    "The clues are organized. Now the real world gets to respond.",
    "Ready. Put this method in the hands of the people who need it."
  ]
};

const NODE_COPY = {
  zh: {
    "about-you": { headline: "我在找你的判断方式。", body: "把材料里的线索聚在一起，先认识你的方法。", activity: "正在寻找反复出现的判断", handoffHeadline: "关键线索找到了，接下来把它们串起来。", handoffBody: "你的回答已保存，正在交给 Corpus。", handoffActivity: "正在把回答交给下一步" },
    corpus: { headline: "我在把线索变成一套方法。", body: "把原则、步骤和边界整理成可以使用的结构。", activity: "正在整理原则、步骤和边界", handoffHeadline: "回答已经接上，方法正在成形。", handoffBody: "正在把你的判断组织成可以工作的 Corpus。", handoffActivity: "正在准备方法结构" },
    review: { headline: "我在找方法哪里还需要校准。", body: "把结果放回真实情境里，看看它是否仍然像你。", activity: "正在对照真实情境", handoffHeadline: "反馈已经记下，准备回到方法里。", handoffBody: "正在把你的判断带回下一版。", handoffActivity: "正在整理反馈" },
    brief: { headline: "我在给用户找一个好的入口。", body: "留下真正会改变后面工作的开始问题。", activity: "正在整理开始问题", handoffHeadline: "入口已经清楚，准备让用户开始工作。", handoffBody: "开始问题正在保存。", handoffActivity: "正在保存入口" },
    complete: { headline: "我在做发布前的最后确认。", body: "看一眼承诺、边界和用户最后拿走的结果。", activity: "正在确认交付边界", handoffHeadline: "线索整理完了，准备交给真实世界。", handoffBody: "正在完成发布准备。", handoffActivity: "正在准备交付" }
  },
  en: {
    "about-you": { headline: "I’m finding the way you make judgments.", body: "Gathering clues from your material before shaping the method.", activity: "Looking for recurring judgments", handoffHeadline: "The key clues are here. Now I’m connecting them.", handoffBody: "Your answers are saved and moving into the Method.", handoffActivity: "Handing your answers to the next step" },
    corpus: { headline: "I’m turning the clues into a method.", body: "Organizing principles, steps, and boundaries into something usable.", activity: "Organizing principles, steps, and boundaries", handoffHeadline: "The answers are connected. The method is taking shape.", handoffBody: "Turning your judgments into a working Method.", handoffActivity: "Preparing the method structure" },
    review: { headline: "I’m finding where the method needs tuning.", body: "Putting the result back into real situations to see if it still sounds like you.", activity: "Comparing real situations", handoffHeadline: "The feedback is noted. Now it goes back into the method.", handoffBody: "Carrying your judgment into the next version.", handoffActivity: "Sorting feedback" },
    brief: { headline: "I’m finding the right entry for the user.", body: "Keeping only the starting questions that change the work ahead.", activity: "Shaping starting questions", handoffHeadline: "The entry is clear. The user can get to work.", handoffBody: "Saving the starting questions.", handoffActivity: "Saving the entry" },
    complete: { headline: "I’m doing one last check before release.", body: "Looking at the promise, boundaries, and result the user takes away.", activity: "Checking delivery boundaries", handoffHeadline: "The clues are organized. Now they can meet the real world.", handoffBody: "Finishing release preparation.", handoffActivity: "Preparing delivery" }
  }
};

export function getCreatorNodeTips(locale = "en", node = "about-you") {
  return (locale === "zh" ? ZH_TIPS : EN_TIPS)[node] ?? EN_TIPS[node] ?? [];
}

export function getCreatorNodeCopy(locale = "en", node = "about-you") {
  return (NODE_COPY[locale] ?? NODE_COPY.en)[node] ?? NODE_COPY.en[node];
}

export const CREATOR_NODE_TIP_NODES = ["about-you", "corpus", "review", "brief", "complete"];
