const MESSAGES = {
  en: {
    research: 'Deep Research', voice: 'Voice Interview', generation: 'Agent Builder', generationShort: 'Builder', caseGeneration: 'Case Builder', caseShort: 'Cases', evaluator: 'Evaluator',
    researchDescription: 'Finds primary evidence and reconstructs how the expert actually thinks.', voiceDescription: 'Draws out tacit judgment through a natural spoken interview.', generationDescription: 'Turns the evidence into an executable expert Agent.', caseDescription: 'Builds one realistic client situation that demands expert judgment.', evaluatorDescription: 'Runs the selected Agent and judges what its result gets right and wrong.',
    idle: 'Waiting for input', running: 'Working', completed: 'Turn complete', failed: 'Run failed', interrupted: 'Stopped',
    chats: 'Chats', newChat: '+ New chat', currentChat: 'Current chat', selectChat: 'Select a chat', progressUnreported: 'Progress not reported', startChat: 'Start a chat', workspaceConnectionLost: 'Workspace connection lost. Reconnecting.', loadingWorkspace: 'Loading workspace…',
    chat: 'Chat', files: 'Files', workspacePanels: 'Workspace panels', viewPrompt: 'View prompt', taskProgress: 'Task progress', awaitingReport: 'Awaiting report', previousProgress: n => `Previous ${n}%`, startChatHeading: 'Start chatting', agent: 'Agent', you: 'You',
    callingTool: name => `Calling ${name}`, thinking: 'Thinking', compacting: 'Organizing context', toolErrorContinuing: name => `${name} returned an error. The Agent is handling it.`, continuing: 'Continuing', reconnecting: 'Connection lost. Reconnecting.', working: 'Working',
    messageLabel: 'Message to Agent', messagePlaceholder: 'Describe the goal, or continue with a revision…', stop: 'Stop', send: 'Send', fileReference: path => `File: ${path}`, fileTooLarge: name => `${name} exceeds 20 MiB`,
    fileCount: n => `${n} file${n === 1 ? '' : 's'}`, attachments: 'Attachments', addFiles: '+ Add files', uploadInputFiles: 'Upload input files', removeFile: path => `Remove ${path}`, dropFiles: 'Drop files here', outputs: 'Outputs', selectFile: path => `Select ${path}`, noFiles: 'No files yet',
    destinationWorkspace: 'Destination chat', sendToChat: 'Send to chat…', sendFiles: n => `Send ${n || ''} file${n === 1 ? '' : 's'}`, chooseFile: 'Choose a file',
    systemPrompt: 'System Prompt', close: 'Close', startVoice: 'Start voice', stopVoice: 'End voice', listening: 'Listening…', voiceUnavailable: 'Voice service unavailable', externalImage: 'external image', imageAlt: alt => `[Image: ${alt}]`,
    toolFailed: 'Failed', toolReturned: 'Returned', toolCalling: 'Calling', toolMissing: 'No result', arguments: 'Arguments', result: 'Result',
    agentPublished: 'Agent published', agentUnpublished: 'Agent not published', selectAgent: 'Select an Agent to evaluate', selectAgentPlaceholder: 'Select an Agent to evaluate…', refresh: 'Refresh',
    draftSaveFailed: 'Could not save the local draft. Save the file before leaving.', markdownFilenameRequired: 'Enter a .md filename', loadingFile: 'Loading file…', addToChat: 'Add to chat', quoteInChat: 'Quote in chat', download: 'Download', read: 'Read', annotateLines: 'Annotate lines', edit: 'Edit', writeRevision: 'Write revision copy', downloadToView: 'Download to view this file.', markdownEditor: 'Markdown editor', revisionFilename: 'Revision copy filename', revisionFilenamePlaceholder: 'suggested-revision.md', stopBeforeSave: 'Stop before saving', save: 'Save', discardEdits: 'Discard edits', lineSelectionHelp: 'Click a line to select it. Shift-click another line to select a range.', commentLabel: 'Comment', commentPlaceholder: 'What should improve in these lines?', replacementLabel: 'Suggested replacement', replacementPlaceholder: 'Suggested replacement (optional)', saveComment: 'Save comment', comments: n => `Comments · ${n}`, exportReview: 'Export REVIEW.md'
  },
  zh: {
    research: '深度研究', voice: '语音访谈', generation: 'Agent 构建', generationShort: '构建', caseGeneration: '案例构建', caseShort: '案例', evaluator: '效果评估',
    researchDescription: '寻找一手证据，还原专家真正如何思考和判断。', voiceDescription: '通过自然的语音访谈，挖出尚未写下的隐性判断。', generationDescription: '把研究证据变成可执行的专家 Agent。', caseDescription: '构造一个真正需要专家判断的现实客户情境。', evaluatorDescription: '运行选中的 Agent，判断结果真正做对和做错了什么。',
    idle: '等待输入', running: '工作中', completed: '本轮结束', failed: '运行失败', interrupted: '已停止', chats: '聊天', newChat: '＋ 新建聊天', currentChat: '当前聊天', selectChat: '选择聊天', progressUnreported: '完成度待报告', startChat: '开始一个聊天', workspaceConnectionLost: '与工作区服务的连接中断，正在重新连接。', loadingWorkspace: '正在读取工作区…',
    chat: '聊天', files: '文件', workspacePanels: '工作区面板', viewPrompt: '查看 Prompt', taskProgress: '任务完成度', awaitingReport: '待报告', previousProgress: n => `上轮 ${n}%`, startChatHeading: '开始聊天', agent: 'Agent', you: '你', callingTool: name => `正在调用 ${name}`, thinking: '正在思考', compacting: '正在整理上下文', toolErrorContinuing: name => `${name} 返回错误，Agent 正在处理`, continuing: '继续工作', reconnecting: '连接中断，正在重新连接', working: '正在工作',
    messageLabel: '给 Agent 的消息', messagePlaceholder: '说明目标，或继续提出修改意见…', stop: '停止', send: '发送', fileReference: path => `文件：${path}`, fileTooLarge: name => `${name} 超过 20 MiB`, fileCount: n => `${n} 份文件`, attachments: '附件', addFiles: '＋ 添加文件', uploadInputFiles: '上传输入文件', removeFile: path => `移除 ${path}`, dropFiles: '拖入文件', outputs: '输出', selectFile: path => `选择 ${path}`, noFiles: '暂无文件', destinationWorkspace: '接收输出的工作区', sendToChat: '发送到聊天…', sendFiles: n => `发送 ${n || ''} 份文件`, chooseFile: '选择文件',
    systemPrompt: 'System Prompt', close: '关闭', startVoice: '开始语音', stopVoice: '结束语音', listening: '正在听…', voiceUnavailable: '语音服务暂不可用', externalImage: '外部图片', imageAlt: alt => `[图片：${alt}]`, toolFailed: '失败', toolReturned: '已返回', toolCalling: '调用中', toolMissing: '未返回', arguments: '参数', result: '结果', agentPublished: 'Agent 已发布', agentUnpublished: 'Agent 尚未发布', selectAgent: '选择要测的 Agent', selectAgentPlaceholder: '选择要测的 Agent…', refresh: '刷新',
    draftSaveFailed: '无法保存本地草稿，请在离开前保存文件。', markdownFilenameRequired: '请填写 .md 文件名', loadingFile: '读取文件…', addToChat: '加入聊天', quoteInChat: '引用到聊天', download: '下载', read: '阅读', annotateLines: '逐行批注', edit: '编辑', writeRevision: '编写修订副本', downloadToView: '请下载查看此文件。', markdownEditor: 'Markdown 编辑器', revisionFilename: '修订副本文件名', revisionFilenamePlaceholder: '建议修订.md', stopBeforeSave: '停止后保存', save: '保存', discardEdits: '放弃编辑', lineSelectionHelp: '点击一行选择；按住 Shift 点击另一行，选择多行。', commentLabel: '批注意见', commentPlaceholder: '这几行哪里需要改进？', replacementLabel: '建议替换文本', replacementPlaceholder: '建议替换文本（可选）', saveComment: '保存批注', comments: n => `批注 · ${n}`, exportReview: '导出 REVIEW.md'
  },
  ja: {
    research: '深掘り調査', voice: '音声インタビュー', generation: 'Agent 構築', generationShort: '構築', caseGeneration: 'ケース構築', caseShort: 'ケース', evaluator: '効果評価',
    researchDescription: '一次情報を集め、専門家が実際にどう考え判断するかを再現します。', voiceDescription: '自然な音声インタビューで、まだ言語化されていない判断を引き出します。', generationDescription: '調査の根拠を、実行可能な専門家 Agent に変換します。', caseDescription: '専門家の判断が本当に必要になる現実的な顧客状況を作ります。', evaluatorDescription: '選択した Agent を実行し、結果の良し悪しを実質的に評価します。',
    idle: '入力待ち', running: '作業中', completed: 'ターン完了', failed: '実行失敗', interrupted: '停止済み', chats: 'チャット', newChat: '＋ 新規チャット', currentChat: '現在のチャット', selectChat: 'チャットを選択', progressUnreported: '進捗未報告', startChat: 'チャットを開始', workspaceConnectionLost: 'ワークスペースとの接続が切れました。再接続しています。', loadingWorkspace: 'ワークスペースを読み込み中…',
    chat: 'チャット', files: 'ファイル', workspacePanels: 'ワークスペースパネル', viewPrompt: 'Prompt を表示', taskProgress: 'タスク進捗', awaitingReport: '報告待ち', previousProgress: n => `前回 ${n}%`, startChatHeading: 'チャットを始める', agent: 'Agent', you: 'あなた', callingTool: name => `${name} を呼び出しています`, thinking: '考えています', compacting: 'コンテキストを整理しています', toolErrorContinuing: name => `${name} でエラーが発生しました。Agent が処理しています。`, continuing: '作業を続けています', reconnecting: '接続が切れました。再接続しています。', working: '作業中',
    messageLabel: 'Agent へのメッセージ', messagePlaceholder: '目標を説明するか、修正内容を伝えてください…', stop: '停止', send: '送信', fileReference: path => `ファイル：${path}`, fileTooLarge: name => `${name} は 20 MiB を超えています`, fileCount: n => `${n} 件のファイル`, attachments: '添付', addFiles: '＋ ファイルを追加', uploadInputFiles: '入力ファイルをアップロード', removeFile: path => `${path} を削除`, dropFiles: 'ここにファイルをドロップ', outputs: '出力', selectFile: path => `${path} を選択`, noFiles: 'ファイルはまだありません', destinationWorkspace: '送信先チャット', sendToChat: 'チャットに送信…', sendFiles: n => `${n || ''} 件のファイルを送信`, chooseFile: 'ファイルを選択',
    systemPrompt: 'System Prompt', close: '閉じる', startVoice: '音声を開始', stopVoice: '音声を終了', listening: '聞いています…', voiceUnavailable: '音声サービスを利用できません', externalImage: '外部画像', imageAlt: alt => `[画像：${alt}]`, toolFailed: '失敗', toolReturned: '返却済み', toolCalling: '呼び出し中', toolMissing: '未返却', arguments: '引数', result: '結果', agentPublished: 'Agent を公開済み', agentUnpublished: 'Agent は未公開', selectAgent: '評価する Agent を選択', selectAgentPlaceholder: '評価する Agent を選択…', refresh: '更新',
    draftSaveFailed: 'ローカル下書きを保存できません。離れる前にファイルを保存してください。', markdownFilenameRequired: '.md のファイル名を入力してください', loadingFile: 'ファイルを読み込み中…', addToChat: 'チャットに追加', quoteInChat: 'チャットに引用', download: 'ダウンロード', read: '読む', annotateLines: '行ごとにコメント', edit: '編集', writeRevision: '修正版を作成', downloadToView: 'ダウンロードして表示してください。', markdownEditor: 'Markdown エディター', revisionFilename: '修正版のファイル名', revisionFilenamePlaceholder: 'suggested-revision.md', stopBeforeSave: '停止してから保存', save: '保存', discardEdits: '編集を破棄', lineSelectionHelp: '行をクリックして選択します。Shift を押しながら別の行をクリックすると範囲選択できます。', commentLabel: 'コメント', commentPlaceholder: 'この行をどう改善すべきですか？', replacementLabel: '置換案', replacementPlaceholder: '置換案（任意）', saveComment: 'コメントを保存', comments: n => `コメント · ${n}`, exportReview: 'REVIEW.md を出力'
  }
};

export const FACTORY_AGENT_I18N_KEYS = Object.keys(MESSAGES.en);
export function createFactoryAgentTranslator(locale = 'en') {
  const messages = { ...MESSAGES.en, ...(MESSAGES[locale] || {}) };
  return (key, ...args) => typeof messages[key] === 'function' ? messages[key](...args) : (messages[key] ?? key);
}
