const MESSAGES = {
  en: {
    research: 'Deep Research', voice: 'Voice Interview', generation: 'Agent Builder', generationShort: 'Builder', caseGeneration: 'Case Builder', caseShort: 'Cases', evaluator: 'Evaluator',
    researchDescription: 'Finds primary evidence and reconstructs how the expert actually thinks.', voiceDescription: 'Draws out tacit judgment through a natural spoken interview.', generationDescription: 'Turns the evidence into an executable expert Agent.', caseDescription: 'Builds one realistic client situation that demands expert judgment.', evaluatorDescription: 'Runs the selected Agent and judges what its result gets right and wrong.',
    idle: 'Waiting for input', running: 'Working', completed: 'Turn complete', failed: 'Run failed', interrupted: 'Stopped',
    chats: 'Chats', newChat: '+ New chat', currentChat: 'Current chat', selectChat: 'Select a chat', progressUnreported: 'Progress not reported', startChat: 'Start a chat', workspaceConnectionLost: 'Workspace connection lost. Reconnecting.', loadingWorkspace: 'Loading workspace…',
    chat: 'Chat', files: 'Files', workspacePanels: 'Workspace panels', viewPrompt: 'View prompt', taskProgress: 'Task progress', awaitingReport: 'Awaiting report', previousProgress: n => `Previous ${n}%`, startChatHeading: 'Start chatting', agent: 'Agent', you: 'You',
    callingTool: name => `Calling ${name}`, thinking: 'Thinking', compacting: 'Organizing context', toolErrorContinuing: name => `${name} returned an error. The Agent is handling it.`, continuing: 'Continuing', reconnecting: 'Connection lost. Reconnecting.', working: 'Working',
    messageLabel: 'Message to Agent', messagePlaceholder: 'Describe the goal, or continue with a revision…', stop: 'Stop', send: 'Send', fileReference: path => `File: ${path}`, fileTooLarge: name => `${name} exceeds 20 MiB`,
    fileCount: n => `${n} file${n === 1 ? '' : 's'}`, attachments: 'Attachments', addFiles: '+ Add files', uploadInputFiles: 'Upload input files', removeFile: path => `Remove ${path}`, dropFiles: 'Drop files here', outputs: 'Outputs', selectFile: path => `Select ${path}`, noFiles: 'No files yet',
    destinationWorkspace: 'Destination chat', sendToChat: 'Send to chat…', sendOutputsTo: 'Continue with', destinationAgent: 'Agent receiving these files', chooseAgent: 'Choose an Agent…', sendFiles: n => `Send ${n || ''} file${n === 1 ? '' : 's'}`, filesSent: (n, name) => `${n} file${n === 1 ? '' : 's'} sent to ${name}.`, handoffHint: 'Selected files become source material in that Agent’s chat.', noHandoffDestination: 'Complete the next Agent’s prerequisites before sending files.', chooseFile: 'Choose a file',
    systemPrompt: 'System Prompt', close: 'Close', startVoice: 'Start voice', stopVoice: 'End voice', listening: 'Listening…', voiceUnavailable: 'Voice service unavailable', externalImage: 'external image', imageAlt: alt => `[Image: ${alt}]`,
    toolFailed: 'Failed', toolReturned: 'Returned', toolCalling: 'Calling', toolMissing: 'No result', arguments: 'Arguments', result: 'Result',
    agentPublished: 'Agent published', agentUnpublished: 'Agent not published', selectAgent: 'Select an Agent to evaluate', selectAgentPlaceholder: 'Select an Agent to evaluate…', refresh: 'Refresh',
    draftSaveFailed: 'Could not save the local draft. Save the file before leaving.', markdownFilenameRequired: 'Enter a .md filename', loadingFile: 'Loading file…', addToChat: 'Add to chat', quoteInChat: 'Quote in chat', download: 'Download', read: 'Read', annotateLines: 'Annotate lines', edit: 'Edit', writeRevision: 'Write revision copy', downloadToView: 'Download to view this file.', markdownEditor: 'Markdown editor', revisionFilename: 'Revision copy filename', revisionFilenamePlaceholder: 'suggested-revision.md', stopBeforeSave: 'Stop before saving', save: 'Save', discardEdits: 'Discard edits', lineSelectionHelp: 'Click a line to select it. Shift-click another line to select a range.', commentLabel: 'Comment', commentPlaceholder: 'What should improve in these lines?', replacementLabel: 'Suggested replacement', replacementPlaceholder: 'Suggested replacement (optional)', saveComment: 'Save comment', comments: n => `Comments · ${n}`, exportReview: 'Export REVIEW.md',
    agentReady: 'Ready to start', agentRunning: 'In progress', agentComplete: 'Complete', agentHasUpdates: 'New material to absorb', agentNeedsAttention: 'Needs attention', agentNeedsPreparation: 'Complete the earlier work first', loadingAgentState: 'Checking what is ready…', agentStateUnavailable: 'The Agent status is not available yet.', finishAgentsFirst: names => `Finish ${names} first`, finishOneAgentFirst: names => `Finish ${names} first`, roleSeparator: ' or ', openToSeeNext: 'Open to see what needs to happen first.', agentBuildsTodo: 'The Agent will make a plan when you open it.', done: 'completed', openAgent: 'Open Agent', stageRunning: n => `${n} in progress`, stageHasUpdates: n => `${n} with new material`, stageComplete: n => `${n} complete`, stageReady: 'Ready to continue', stageWaiting: 'Waiting for earlier work', nextSteps: 'Next', beforeStarting: 'Before you start', completeUpstreamWork: 'Finish the work below so this Agent has what it needs.', completeOneOf: 'Then complete one of these:', goThere: 'Go there', newWorkAvailable: 'There is new material to absorb', newWorkAvailableBody: names => `${names} changed after this result was made.`, newWorkAvailableBodyGeneric: 'Earlier work changed after this result was made.', viewAgent: name => `View ${name}`, improveWithLatest: 'Improve with the latest', useLatestMessage: 'Use the latest upstream work to revisit and improve this result. Preserve what remains strong, update what changed, and write the complete revised output.', completeDependenciesToStart: 'Finish the earlier work before starting this Agent.', factory: 'Factory', product: 'Product', backToStage: 'Back to stage', allStages: 'All stages', sourcesStage: 'Collect sources', sourcesStageDescription: 'Build substantial, traceable context about the Creator.', generationStage: 'Build the Agent', generationStageDescription: "Turn the Creator's judgment into an Agent that can do real work.", evaluationStage: 'Test the result', evaluationStageDescription: 'Use a complete client case to test and improve the result.', uploadSources: 'Add source material', uploadSourcesBody: 'Add existing documents, interviews, courses, and other original material.', chooseFiles: 'Choose files', comingSoon: 'Coming soon', futureSources: 'Google Drive · Notion', futureSourcesBody: 'Choose material from an existing knowledge base.', factoryPromise: 'Turn a Creator into an Agent people can rely on.', todo: 'Plan', startAgent: 'Start Agent', tryAgain: 'Try again', agentSetupUnavailable: 'The Agent setup is temporarily unavailable.', unknownFactoryError: 'Factory could not complete that action.'
  },
  zh: {
    research: '深度研究', voice: '语音访谈', generation: 'Agent 构建', generationShort: '构建', caseGeneration: '案例构建', caseShort: '案例', evaluator: '效果评估',
    researchDescription: '寻找一手证据，还原专家真正如何思考和判断。', voiceDescription: '通过自然的语音访谈，挖出尚未写下的隐性判断。', generationDescription: '把研究证据变成可执行的专家 Agent。', caseDescription: '构造一个真正需要专家判断的现实客户情境。', evaluatorDescription: '运行选中的 Agent，判断结果真正做对和做错了什么。',
    idle: '等待输入', running: '工作中', completed: '本轮结束', failed: '运行失败', interrupted: '已停止', chats: '聊天', newChat: '＋ 新建聊天', currentChat: '当前聊天', selectChat: '选择聊天', progressUnreported: '完成度待报告', startChat: '开始一个聊天', workspaceConnectionLost: '与工作区服务的连接中断，正在重新连接。', loadingWorkspace: '正在读取工作区…',
    chat: '聊天', files: '文件', workspacePanels: '工作区面板', viewPrompt: '查看 Prompt', taskProgress: '任务完成度', awaitingReport: '待报告', previousProgress: n => `上轮 ${n}%`, startChatHeading: '开始聊天', agent: 'Agent', you: '你', callingTool: name => `正在调用 ${name}`, thinking: '正在思考', compacting: '正在整理上下文', toolErrorContinuing: name => `${name} 返回错误，Agent 正在处理`, continuing: '继续工作', reconnecting: '连接中断，正在重新连接', working: '正在工作',
    messageLabel: '给 Agent 的消息', messagePlaceholder: '说明目标，或继续提出修改意见…', stop: '停止', send: '发送', fileReference: path => `文件：${path}`, fileTooLarge: name => `${name} 超过 20 MiB`, fileCount: n => `${n} 份文件`, attachments: '附件', addFiles: '＋ 添加文件', uploadInputFiles: '上传输入文件', removeFile: path => `移除 ${path}`, dropFiles: '拖入文件', outputs: '输出', selectFile: path => `选择 ${path}`, noFiles: '暂无文件', destinationWorkspace: '接收输出的工作区', sendToChat: '发送到聊天…', sendOutputsTo: '交给下一个 Agent', destinationAgent: '接收这些文件的 Agent', chooseAgent: '选择 Agent…', sendFiles: n => `发送 ${n || ''} 份文件`, filesSent: (n, name) => `已将 ${n} 份文件交给${name}。`, handoffHint: '勾选的文件会成为该 Agent 聊天中的资料。', noHandoffDestination: '先完成下一个 Agent 所需的前置工作，再发送文件。', chooseFile: '选择文件',
    systemPrompt: 'System Prompt', close: '关闭', startVoice: '开始语音', stopVoice: '结束语音', listening: '正在听…', voiceUnavailable: '语音服务暂不可用', externalImage: '外部图片', imageAlt: alt => `[图片：${alt}]`, toolFailed: '失败', toolReturned: '已返回', toolCalling: '调用中', toolMissing: '未返回', arguments: '参数', result: '结果', agentPublished: 'Agent 已发布', agentUnpublished: 'Agent 尚未发布', selectAgent: '选择要测的 Agent', selectAgentPlaceholder: '选择要测的 Agent…', refresh: '刷新',
    draftSaveFailed: '无法保存本地草稿，请在离开前保存文件。', markdownFilenameRequired: '请填写 .md 文件名', loadingFile: '读取文件…', addToChat: '加入聊天', quoteInChat: '引用到聊天', download: '下载', read: '阅读', annotateLines: '逐行批注', edit: '编辑', writeRevision: '编写修订副本', downloadToView: '请下载查看此文件。', markdownEditor: 'Markdown 编辑器', revisionFilename: '修订副本文件名', revisionFilenamePlaceholder: '建议修订.md', stopBeforeSave: '停止后保存', save: '保存', discardEdits: '放弃编辑', lineSelectionHelp: '点击一行选择；按住 Shift 点击另一行，选择多行。', commentLabel: '批注意见', commentPlaceholder: '这几行哪里需要改进？', replacementLabel: '建议替换文本', replacementPlaceholder: '建议替换文本（可选）', saveComment: '保存批注', comments: n => `批注 · ${n}`, exportReview: '导出 REVIEW.md',
    agentReady: '可以开始', agentRunning: '正在进行', agentComplete: '已完成', agentHasUpdates: '有新内容可吸收', agentNeedsAttention: '需要处理', agentNeedsPreparation: '先完成前面的工作', loadingAgentState: '正在确认进度…', agentStateUnavailable: '暂时无法读取 Agent 的进度。', finishAgentsFirst: names => `先完成${names}`, finishOneAgentFirst: names => `先完成${names}中的一项`, roleSeparator: '或', openToSeeNext: '打开查看开始前要完成什么。', agentBuildsTodo: '打开后，Agent 会建立自己的计划。', done: '已完成', openAgent: '打开 Agent', stageRunning: n => `${n} 个正在进行`, stageHasUpdates: n => `${n} 个有新内容`, stageComplete: n => `${n} 个已完成`, stageReady: '可以继续', stageWaiting: '等待前面的工作', nextSteps: '接下来', beforeStarting: '开始前，先完成', completeUpstreamWork: '先把下面的工作做好，这个 Agent 才有足够的内容继续。', completeOneOf: '然后至少完成一项：', goThere: '去看看', newWorkAvailable: '有新内容可以吸收', newWorkAvailableBody: names => `${names}在这份成果完成后又有了新内容。`, newWorkAvailableBodyGeneric: '这份成果完成后，前面的工作又有了新内容。', viewAgent: name => `去看看${name}`, improveWithLatest: '用最新内容再完善', useLatestMessage: '请吸收上游 Agent 的最新成果，重新检查并完善当前结果。保留仍然成立的部分，更新已经变化的内容，并写出完整的修订版。', completeDependenciesToStart: '先完成前面的工作，再开始这个 Agent。', factory: 'Factory', product: '产品', backToStage: '返回阶段', allStages: '所有阶段', sourcesStage: '收集资料', sourcesStageDescription: '建立足够厚实、可追溯的 Creator 资料。', generationStage: '生成 Agent', generationStageDescription: '把 Creator 的判断变成可以真实工作的 Agent。', evaluationStage: '测试效果', evaluationStageDescription: '用完整的客户案例检验并改进结果。', uploadSources: '上传资料', uploadSourcesBody: '加入已有文档、访谈、课程和其他原始材料。', chooseFiles: '选择文件', comingSoon: '即将推出', futureSources: 'Google Drive · Notion', futureSourcesBody: '从已有知识库选择资料。', factoryPromise: '把一位 Creator 变成真正有用的 Agent。', todo: '计划', startAgent: '开始 Agent', tryAgain: '再试一次', agentSetupUnavailable: 'Agent 配置暂时不可用。', unknownFactoryError: '暂时无法完成这项操作。'
  },
  ja: {
    research: '深掘り調査', voice: '音声インタビュー', generation: 'Agent 構築', generationShort: '構築', caseGeneration: 'ケース構築', caseShort: 'ケース', evaluator: '効果評価',
    researchDescription: '一次情報を集め、専門家が実際にどう考え判断するかを再現します。', voiceDescription: '自然な音声インタビューで、まだ言語化されていない判断を引き出します。', generationDescription: '調査の根拠を、実行可能な専門家 Agent に変換します。', caseDescription: '専門家の判断が本当に必要になる現実的な顧客状況を作ります。', evaluatorDescription: '選択した Agent を実行し、結果の良し悪しを実質的に評価します。',
    idle: '入力待ち', running: '作業中', completed: 'ターン完了', failed: '実行失敗', interrupted: '停止済み', chats: 'チャット', newChat: '＋ 新規チャット', currentChat: '現在のチャット', selectChat: 'チャットを選択', progressUnreported: '進捗未報告', startChat: 'チャットを開始', workspaceConnectionLost: 'ワークスペースとの接続が切れました。再接続しています。', loadingWorkspace: 'ワークスペースを読み込み中…',
    chat: 'チャット', files: 'ファイル', workspacePanels: 'ワークスペースパネル', viewPrompt: 'Prompt を表示', taskProgress: 'タスク進捗', awaitingReport: '報告待ち', previousProgress: n => `前回 ${n}%`, startChatHeading: 'チャットを始める', agent: 'Agent', you: 'あなた', callingTool: name => `${name} を呼び出しています`, thinking: '考えています', compacting: 'コンテキストを整理しています', toolErrorContinuing: name => `${name} でエラーが発生しました。Agent が処理しています。`, continuing: '作業を続けています', reconnecting: '接続が切れました。再接続しています。', working: '作業中',
    messageLabel: 'Agent へのメッセージ', messagePlaceholder: '目標を説明するか、修正内容を伝えてください…', stop: '停止', send: '送信', fileReference: path => `ファイル：${path}`, fileTooLarge: name => `${name} は 20 MiB を超えています`, fileCount: n => `${n} 件のファイル`, attachments: '添付', addFiles: '＋ ファイルを追加', uploadInputFiles: '入力ファイルをアップロード', removeFile: path => `${path} を削除`, dropFiles: 'ここにファイルをドロップ', outputs: '出力', selectFile: path => `${path} を選択`, noFiles: 'ファイルはまだありません', destinationWorkspace: '送信先チャット', sendToChat: 'チャットに送信…', sendOutputsTo: '次の Agent に引き継ぐ', destinationAgent: 'ファイルを受け取る Agent', chooseAgent: 'Agent を選択…', sendFiles: n => `${n || ''} 件のファイルを送信`, filesSent: (n, name) => `${n} 件のファイルを${name}に送りました。`, handoffHint: '選択したファイルは、その Agent のチャット資料になります。', noHandoffDestination: '次の Agent の前提作業を完了してからファイルを送ってください。', chooseFile: 'ファイルを選択',
    systemPrompt: 'System Prompt', close: '閉じる', startVoice: '音声を開始', stopVoice: '音声を終了', listening: '聞いています…', voiceUnavailable: '音声サービスを利用できません', externalImage: '外部画像', imageAlt: alt => `[画像：${alt}]`, toolFailed: '失敗', toolReturned: '返却済み', toolCalling: '呼び出し中', toolMissing: '未返却', arguments: '引数', result: '結果', agentPublished: 'Agent を公開済み', agentUnpublished: 'Agent は未公開', selectAgent: '評価する Agent を選択', selectAgentPlaceholder: '評価する Agent を選択…', refresh: '更新',
    draftSaveFailed: 'ローカル下書きを保存できません。離れる前にファイルを保存してください。', markdownFilenameRequired: '.md のファイル名を入力してください', loadingFile: 'ファイルを読み込み中…', addToChat: 'チャットに追加', quoteInChat: 'チャットに引用', download: 'ダウンロード', read: '読む', annotateLines: '行ごとにコメント', edit: '編集', writeRevision: '修正版を作成', downloadToView: 'ダウンロードして表示してください。', markdownEditor: 'Markdown エディター', revisionFilename: '修正版のファイル名', revisionFilenamePlaceholder: 'suggested-revision.md', stopBeforeSave: '停止してから保存', save: '保存', discardEdits: '編集を破棄', lineSelectionHelp: '行をクリックして選択します。Shift を押しながら別の行をクリックすると範囲選択できます。', commentLabel: 'コメント', commentPlaceholder: 'この行をどう改善すべきですか？', replacementLabel: '置換案', replacementPlaceholder: '置換案（任意）', saveComment: 'コメントを保存', comments: n => `コメント · ${n}`, exportReview: 'REVIEW.md を出力',
    agentReady: '開始できます', agentRunning: '進行中', agentComplete: '完了', agentHasUpdates: '取り込める新しい内容があります', agentNeedsAttention: '対応が必要です', agentNeedsPreparation: '先に前の作業を完了してください', loadingAgentState: '進捗を確認中…', agentStateUnavailable: 'Agent の進捗をまだ読み込めません。', finishAgentsFirst: names => `先に${names}を完了してください`, finishOneAgentFirst: names => `先に${names}のいずれかを完了してください`, roleSeparator: 'または', openToSeeNext: '開いて、先に必要なことを確認します。', agentBuildsTodo: '開くと Agent が作業計画を作ります。', done: '完了', openAgent: 'Agent を開く', stageRunning: n => `${n} 件が進行中`, stageHasUpdates: n => `${n} 件に新しい内容`, stageComplete: n => `${n} 件が完了`, stageReady: '続けられます', stageWaiting: '前の作業を待っています', nextSteps: '次にすること', beforeStarting: '開始前に、先に完了', completeUpstreamWork: 'この Agent に必要な内容が揃うよう、以下を先に完了してください。', completeOneOf: '次のうち少なくとも一つを完了：', goThere: '見に行く', newWorkAvailable: '取り込める新しい内容があります', newWorkAvailableBody: names => `この成果の完了後に、${names}が更新されました。`, newWorkAvailableBodyGeneric: 'この成果の完了後に、前の作業が更新されました。', viewAgent: name => `${name}を見に行く`, improveWithLatest: '最新内容で改善', useLatestMessage: '上流 Agent の最新成果を取り込み、現在の結果を再確認して改善してください。引き続き有効な部分は残し、変更された内容を更新し、完全な改訂版を作成してください。', completeDependenciesToStart: '前の作業を完了してから、この Agent を開始してください。', factory: 'Factory', product: 'プロダクト', backToStage: 'ステージに戻る', allStages: 'すべてのステージ', sourcesStage: '資料を集める', sourcesStageDescription: 'Creator について、十分な厚みと追跡可能性のある資料を整えます。', generationStage: 'Agent を作る', generationStageDescription: 'Creator の判断を、実際に仕事ができる Agent に変えます。', evaluationStage: '効果を確かめる', evaluationStageDescription: '完全な顧客ケースで結果を検証し、改善します。', uploadSources: '資料を追加', uploadSourcesBody: '既存の文書、インタビュー、コース、その他の原資料を追加します。', chooseFiles: 'ファイルを選ぶ', comingSoon: '近日公開', futureSources: 'Google Drive · Notion', futureSourcesBody: '既存のナレッジベースから資料を選びます。', factoryPromise: 'Creator を、人々が信頼できる Agent に変えます。', todo: '計画', startAgent: 'Agent を開始', tryAgain: 'もう一度試す', agentSetupUnavailable: 'Agent の設定を一時的に利用できません。', unknownFactoryError: 'この操作を完了できませんでした。'
  }
};

export const FACTORY_AGENT_I18N_KEYS = Object.keys(MESSAGES.en);
export const FACTORY_AGENT_I18N_KEYS_BY_LOCALE = Object.fromEntries(Object.entries(MESSAGES).map(([locale, messages]) => [locale, Object.keys(messages)]));
export function createFactoryAgentTranslator(locale = 'en') {
  const messages = { ...MESSAGES.en, ...(MESSAGES[locale] || {}) };
  return (key, ...args) => typeof messages[key] === 'function' ? messages[key](...args) : (messages[key] ?? key);
}
