export type FactoryStage =
  | "extracting_evidence"
  | "awaiting_creator_answers"
  | "compiling_corpus"
  | "evaluating_development"
  | "evaluating_regression"
  | "evaluating_heldout"
  | "review_required"
  | "ready"
  | "needs_attention";

export type ArtifactRef = {
  path: string;
  sha256: string;
  createdAt: string;
  /** Control-plane identity when the Postgres graph is enabled. */
  artifactId?: string;
  sealed?: true;
};

/**
 * A sealed Question artifact plus its distinct answer-authorization identity.
 * `sha256` verifies file bytes; `batchId` is run-scoped and cannot be reused
 * merely because two runs generated byte-identical Questions.
 */
export type QuestionBatchArtifactRef = ArtifactRef & {
  sealed: true;
  batchNonce: string;
  batchId: string;
};

export type CreatorQuestion = {
  id: string;
  question: string;
  intent?: string;
  leakageGroup?: string;
  /** A provenance hypothesis needs explicit Creator confirmation before compilation. */
  kind?: "behavior" | "provenance_confirmation";
};

export type CreatorQa = CreatorQuestion & {
  answer: string;
};

export type CreatorAnswerInput = {
  questionId: string;
  answer: string;
};

export type EvaluationVerdict = {
  pass: boolean;
  diagnosis: string;
  fewShot: string;
  corpusReflection: string;
  raw: string;
};

export type FactoryAgentProduct = {
  id: string;
  name: string;
  description?: string;
  promise?: string;
  boundaries?: string[];
  presentation?: Record<string, unknown>;
};

export type FactoryAgentTool =
  | {
      id: "hatch.web_search";
      kind: "hatch_builtin";
      capability: "web_search";
      description?: string;
    }
  | {
      id: "hatch.file_search";
      kind: "hatch_builtin";
      capability: "file_search";
      description?: string;
    }
  | {
      id: string;
      kind: "local_harness";
      capability: "filesystem" | "shell" | "git";
      description?: string;
    }
  | {
      id: string;
      kind: "http_function";
      connection_ref: string;
      operation: string;
      description?: string;
      input_schema?: Record<string, unknown>;
    }
  | {
      id: string;
      kind: "mcp_tool";
      connection_ref: string;
      tool_name: string;
      description?: string;
      input_schema?: Record<string, unknown>;
    };

export type FactorySource = {
  id: string;
  authority: "creator_current" | "creator_example" | "private_material" | "public_context";
  title: string;
  content: string;
  /** Native image bytes are passed to multimodal Factory nodes, never flattened into text. */
  image?: {
    mediaType: "image/jpeg" | "image/png" | "image/webp";
    base64: string;
    sha256: string;
  };
};

export type SourceProjection =
  | {
      kind: "markdown";
      mediaType: "text/markdown";
      contentRef: string;
      sha256: string;
      bytes: number;
    }
  | {
      kind: "image";
      mediaType: "image/jpeg" | "image/png" | "image/webp";
      contentRef: string;
      sha256: string;
      bytes: number;
    };

export type SourceDocumentRecord = {
  id: string;
  creatorId: string;
  productId: string;
  displayName: string;
  mediaType: string;
  originalObjectRef?: string;
  projection: SourceProjection;
  createdAt: string;
  updatedAt: string;
};

export type SourceSnapshotRecord = {
  id: string;
  creatorId: string;
  productId?: string;
  version: number;
  documentIds: string[];
  manifestSha256: string;
  lockedAt: string;
  createdAt: string;
};

/**
 * A content-addressed proof of the complete local directory snapshot that was
 * converted into `FactorySource[]` at the CLI boundary. It deliberately omits
 * the host's absolute pack path; `path` values are canonical POSIX paths
 * relative to the authorized pack root.
 */
export type FactorySourceManifest = {
  contract_version: "1";
  completeness: "all_regular_files";
  creator_directory: string;
  authority: FactorySource["authority"];
  integrity:
    | {
        /** No operator-supplied inventory: proof covers the frozen recursive directory snapshot. */
        kind: "directory_snapshot";
      }
    | {
        kind: "checksums_sha256";
        path: string;
        sha256: string;
      }
    | {
        kind: "manifest";
        path: string;
        sha256: string;
      };
  file_count: number;
  total_bytes: number;
  root_digest: string;
  files: Array<{
    source_id: string;
    path: string;
    title: string;
    bytes: number;
    sha256: string;
  }>;
};

export type MaterializedAgentCorpus = {
  /** Candidate-relative path whose root contains agent.json. */
  rootPath: string;
  manifest: ArtifactRef;
  /** Model-visible runtime assets, retained as immutable refs for Creator review. */
  assets?: {
    system: ArtifactRef;
    skills: Array<{
      id: string;
      instruction: ArtifactRef;
      references: Array<{ id: string; kind: "method" | "style" | "example" | "few_shots"; asset: ArtifactRef }>;
    }>;
    knowledge: Array<{ id: string; asset: ArtifactRef }>;
  };
  syntheticQa: ArtifactRef;
  heldOut: ArtifactRef;
  /** Whole-corpus digest returned by the Registry verifier, not an asset digest. */
  digest: string;
  verifiedAt: string;
};

export type CorpusCandidate = {
  version: number;
  systemInstructions: ArtifactRef;
  compileRecord: ArtifactRef;
  reason: "initial" | "development_calibration" | "development_failure" | "heldout_failure" | "completeness_failure";
  /** Optional so states written before deterministic preservation baselines remain readable. */
  completeness?: "PASS" | "FAIL";
  agentCorpus?: MaterializedAgentCorpus;
};

/**
 * The latest complete compiler output rejected by a deterministic release
 * guard. It is a repair input only: it is never an accepted continuity
 * baseline, a publishable candidate, or part of the accepted version high-water
 * mark.
 */
export type RejectedCorpusRepairTarget = {
  attempt: number;
  candidateVersion: number;
  compilation: ArtifactRef;
  failureReport: ArtifactRef;
  reason: "release_guard" | "completeness_failure";
};

/**
 * A complete compiler result whose deterministic release audit exhausted a
 * bounded analysis budget. Retry always re-reads this content-addressed draft
 * and re-runs the host guard before any new Corpus LLM call is permitted.
 */
export type PendingGuardCandidate = {
  candidateVersion: number;
  compilation: ArtifactRef;
  reason: CorpusCandidate["reason"];
  /** Latest position-only INCONCLUSIVE report, when one has been emitted. */
  guardReport?: ArtifactRef;
};

export type QaCaseCheckpoint = {
  /** Digest of the complete canonical Creator QA case; no QA content lives in state. */
  canonicalDigest: string;
  hatchResult?: ArtifactRef;
  evaluation?: ArtifactRef;
};

/**
 * Durable, content-bound progress for exactly one in-flight QA set. Results
 * live in immutable artifacts; state contains only identities, digests, order,
 * seals, and references.
 */
export type ActiveQaEvaluationScope = {
  contractVersion: "1";
  label: string;
  qaSetSha256: string;
  caseOrder: string[];
  corpusVersion: number;
  corpusDigest: string;
  sealed: boolean;
  cases: QaCaseCheckpoint[];
};

export type FactorySourceImageArtifact = {
  sourceId: string;
  mediaType: "image/jpeg" | "image/png" | "image/webp";
  artifact: ArtifactRef;
};

export type FactoryRunState = {
  contractVersion: "1";
  runId: string;
  creator: { id: string; name: string };
  agentId: string;
  product: FactoryAgentProduct;
  /** Optional only so durable states written before tool declarations remain readable. */
  tools?: FactoryAgentTool[];
  productName: string;
  productId?: string;
  /** Stable Product Run lineage; `runId` remains the executable revision id. */
  distillationRunId?: string;
  revisionId?: string;
  revisionNumber?: number;
  parentRevisionId?: string;
  sourceSnapshotId?: string;
  stage: FactoryStage;
  config: {
    developmentQuestions: number;
    heldoutQuestions: number;
    maxCorpusRevisions: number;
  };
  artifacts: {
    productPromise: ArtifactRef;
    sourcePacket: ArtifactRef;
    /** Present for CLI runs created from an exhaustive local source_scope. */
    sourceManifest?: ArtifactRef;
    sourceImages?: FactorySourceImageArtifact[];
    evidence?: ArtifactRef;
    developmentQa?: ArtifactRef;
    currentQuestionBatch?: QuestionBatchArtifactRef;
    creatorAnswerTemplate?: ArtifactRef;
    corpusCandidates: CorpusCandidate[];
    /** Optional for states created before rejected-draft repair was durable. */
    rejectedCorpusRepairTarget?: RejectedCorpusRepairTarget;
    /** Optional durable checkpoint for a bounded deterministic guard recheck. */
    pendingGuardCandidate?: PendingGuardCandidate;
    evaluationRounds: ArtifactRef[];
    latestRegressionEvaluation?: ArtifactRef;
    regressionSet?: ArtifactRef;
    heldoutRounds: ArtifactRef[];
    latestHeldoutEvaluation?: ArtifactRef;
    /** Immutable Creator review/correction context carried into a revision. */
    reviewContext?: ArtifactRef;
  };
  pendingQuestionBatch?: {
    purpose: "initial" | "replacement_heldout";
    count: number;
  };
  compileReason?: CorpusCandidate["reason"];
  /** Current calibration loop only; historical rounds remain append-only audit artifacts. */
  calibrationFeedback?: ArtifactRef[];
  replacementHeldoutNeeded: number;
  corpusRevisionCount: number;
  developmentEvaluated: boolean;
  /** Optional for durable states created before per-QA checkpointing. */
  activeQaEvaluation?: ActiveQaEvaluationScope;
  retryStage?: Exclude<FactoryStage, "ready" | "needs_attention" | "awaiting_creator_answers">;
  /** Sealed held-out failures pause here until the Creator supplies a correction. */
  pendingReview?: {
    kind: "heldout_failure";
    report: ArtifactRef;
    failedCount: number;
  };
  lastError?: string;
  createdAt: string;
  updatedAt: string;
};

export type FactoryStartInput = {
  runId?: string;
  creator: { id: string; name: string };
  /** Optional for backwards-compatible callers; Factory derives a stable valid id when omitted. */
  agentId?: string;
  product?: Partial<FactoryAgentProduct>;
  /** Declarative Agent Corpus requirements; Factory never asks an LLM to invent tools. */
  tools?: FactoryAgentTool[];
  productName: string;
  /** Stable Distillation Product identity; a run lineage can receive revisions. */
  productId?: string;
  distillationRunId?: string;
  revisionId?: string;
  revisionNumber?: number;
  parentRevisionId?: string;
  productPromise: string;
  sources: FactorySource[];
  /** Immutable Source Library snapshot resolved before the worker starts. */
  sourceSnapshotId?: string;
  /** Frozen source-scope proof. Legacy inline-source callers omit this. */
  sourceManifest?: FactorySourceManifest;
  /** Identity-only input for a correction/review-created revision. */
  reviewContext?: {
    sourceRunId: string;
    artifact: ArtifactRef;
    /** Safe Creator-authored correction feedback; never contains sealed cases. */
    calibrationArtifact?: ArtifactRef;
    mode: "correction" | "heldout_correction" | "question_replacement";
  };
  config?: Partial<FactoryRunState["config"]>;
};

export type FactoryPromptPurpose =
  | "evidence.extract"
  | "eval.generate_questions"
  | "eval.judge_result"
  | "eval.audit_corpus"
  | "corpus.compile";

/**
 * Small host-owned facts that cannot safely be recovered by scraping the
 * natural-language prompt. The model still receives the complete loose input;
 * this contract only tells the local submission FSM what a complete output is.
 */
export type FactoryOutputContract =
  | { kind: "evidence_ledger"; requiredSections: string[] }
  | { kind: "question_set"; expectedCount: number }
  | { kind: "evaluation_verdict" }
  | { kind: "corpus_audit" }
  | { kind: "corpus_compilation"; availableToolIds: string[] };

export type FactoryExecutionStatus = "running" | "completed" | "failed" | "aborted" | "abandoned";

export type FactorySubmissionToolName =
  | "restart_submission"
  | "submit_evidence_section"
  | "finalize_evidence"
  | "submit_question"
  | "finalize_questions"
  | "submit_evaluation"
  | "finalize_evaluation"
  | "submit_corpus_audit"
  | "finalize_corpus_audit"
  | "submit_system_instructions"
  | "submit_skill"
  | "submit_reference"
  | "submit_knowledge"
  | "submit_corpus_audit_section"
  | "finalize_corpus";

/**
 * Content-free diagnostics for a failed local submission session. This is
 * deliberately bounded to host-owned enums and counters: prompts, arguments,
 * authored IDs, receipts, errors, hashes, and artifact contents are forbidden.
 */
export type FactoryPromptFailureTelemetry = {
  contractVersion: "1";
  code:
    | "provider_incomplete"
    | "provider_quota"
    | "provider_error"
    | "aborted"
    | "exact_submission_cycle"
    | "stopped_without_finalize"
    | "submission_protocol_error"
    | "unknown";
  turnsObserved: number;
  toolTurnsObserved: number;
  toolCallsRequested: number;
  toolResultsObserved: number;
  toolErrorsObserved: number;
  exactCycleKind?:
    | "missing_finalizer"
    | "repeated_final_validation"
    | "repeated_batch_error"
    | "repeated_no_progress";
  lastToolTurn?: {
    callsRequested: number;
    results: number;
    errors: number;
    accepted: number;
    idempotent: number;
    rejected: number;
    toolNames: FactorySubmissionToolName[];
    finalizerOutcome: "absent" | "accepted" | "rejected" | "error";
    /** Host-owned, content-free validator code for a rejected finalizer. */
    finalizerValidationCode?: string;
    finalizerPosition: "absent" | "last" | "not_last" | "multiple";
    transaction: "finalized" | "retained" | "cleared" | "rolled_back" | "no_draft";
  };
};

/**
 * Deliberately small, allow-listed metadata for durable execution timing.
 * Prompt/output/question/answer/error content must never be added here: a
 * timing sidecar may describe a sealed execution without declassifying it.
 */
export type FactoryExecutionMetadata =
  | {
      boundary: "factory_llm";
      purpose: FactoryPromptPurpose;
      promptVersion: string;
      provider: string;
      model: string;
    }
  | {
      boundary: "hatch_product_runtime";
      purpose: "hatch.candidate";
      corpusVersion: number;
      corpusDigest: string;
    };

export type FactoryExecutionTiming = {
  contractVersion: "1";
  executionId: string;
  runId: string;
  status: FactoryExecutionStatus;
  /** Wall-clock timestamps are for operator orientation only. */
  startedAt: string;
  completedAt?: string;
  /** Always measured from a monotonic clock, never derived from timestamps. Absent for abandoned work. */
  elapsedMs?: number;
  sealed: boolean;
  metadata: FactoryExecutionMetadata;
  /** Present only on a failed/aborted Factory LLM execution. */
  failureTelemetry?: FactoryPromptFailureTelemetry;
};

export type FactoryPromptCall = {
  purpose: FactoryPromptPurpose;
  systemPrompt: string;
  prompt: string;
  outputContract?: FactoryOutputContract;
  /** Optional native images for multimodal Factory models; never serialized into text packets. */
  images?: Array<{
    mediaType: "image/jpeg" | "image/png" | "image/webp";
    base64: string;
  }>;
  /** Host-only synchronous observation; never serialized into an LLM request. */
  reportFailureTelemetry?: (telemetry: FactoryPromptFailureTelemetry) => void;
  /** Execution cancellation only; never part of a persisted prompt contract. */
  signal?: AbortSignal;
};

export type FactoryPromptRunner = (call: FactoryPromptCall) => Promise<string>;

export type HatchCandidateExecution = {
  runId: string;
  corpusVersion: number;
  /** Absolute snapshot root containing a verified agent.json. */
  agentCorpusRoot: string;
  creatorId: string;
  agentId: string;
  /** Whole-corpus digest expected from Hatch session.ready. */
  corpusDigest: string;
  systemInstructions: string;
  question: string;
  signal?: AbortSignal;
};

export type HatchCandidateResult = {
  output: string;
  runtimeRunId?: string;
  corpusDigest: string;
  finishReason?: "stop";
  terminalStatus?: "completed";
  protocolEvents?: Array<{ type: string; status?: string; name?: string }>;
  protocolTraceTruncated?: boolean;
};

/** Product Runtime execution seam; this is not a fourth Factory LLM role. */
export type HatchCandidateExecutor = (execution: HatchCandidateExecution) => Promise<string | HatchCandidateResult>;

export type QaEvaluation = {
  qa: CreatorQa;
  hatchResult: string;
  verdict: EvaluationVerdict;
};

export type FactoryExecutionControl = {
  /** Abort in-flight model/runtime work when the durable lease is lost. */
  signal?: AbortSignal;
  /** Fence every durable file commit against the current lease owner/token. */
  beforeCommit?: () => Promise<void>;
};
